# Generated by Django 4.2 on 2025-11-13 23:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0009_auto_20251023_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailtransaksi',
            old_name='produk',
            new_name='idProduk',
        ),
        migrations.RenameField(
            model_name='detailtransaksi',
            old_name='transaksi',
            new_name='idTransaksi',
        ),
        migrations.RenameField(
            model_name='diskonpelanggan',
            old_name='pelanggan',
            new_name='idPelanggan',
        ),
        migrations.RenameField(
            model_name='diskonpelanggan',
            old_name='produk',
            new_name='idProduk',
        ),
        migrations.RenameField(
            model_name='notifikasi',
            old_name='pelanggan',
            new_name='idPelanggan',
        ),
        migrations.RenameField(
            model_name='transaksi',
            old_name='pelanggan',
            new_name='idPelanggan',
        ),
        migrations.AlterField(
            model_name='detailtransaksi',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='diskonpelanggan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notifikasi',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='produk',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='tanggal',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
