# Generated by Django 4.2 on 2025-11-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0010_rename_produk_detailtransaksi_idproduk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diskonpelanggan',
            name='berlaku_sampai',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Berlaku Sampai'),
        ),
        migrations.AddField(
            model_name='diskonpelanggan',
            name='minimum_cart_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Minimum Cart Total'),
        ),
        migrations.AddField(
            model_name='diskonpelanggan',
            name='scope_diskon',
            field=models.CharField(choices=[('ALL_PRODUCTS', 'All Products'), ('CART_THRESHOLD', 'Cart Threshold'), ('SINGLE_PRODUCT', 'Single Product')], default='SINGLE_PRODUCT', max_length=50, verbose_name='Scope Diskon'),
        ),
    ]
