# Generated by Django 4.2 on 2025-11-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0011_diskonpelanggan_berlaku_sampai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='foto_pengiriman',
            field=models.ImageField(blank=True, null=True, upload_to='verifikasi_pengiriman/', verbose_name='Foto Verifikasi Pengiriman'),
        ),
    ]
