# Generated by Django 4.2 on 2025-11-27 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0012_transaksi_foto_pengiriman'),
    ]

    operations = [
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255, verbose_name='Nama Karyawan')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=128, verbose_name='Password')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dibuat Pada')),
            ],
            options={
                'verbose_name_plural': 'Karyawan',
                'db_table': 'karyawan',
            },
        ),
    ]
