# Generated by Django 4.2 on 2025-12-09 06:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0013_karyawan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='tanggal',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
