# Generated by Django 4.2 on 2025-12-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0014_alter_transaksi_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='alamat_pengiriman',
            field=models.TextField(verbose_name='Alamat Pengiriman'),
        ),
    ]
